export const TOPSTORIES_REQ = "TOPSTORIES_REQ";
export const TOPSTORIES_SUCCESS = "TOPSTORIES_SUCCESS";
export const TOPSTORIES_FAILURE = "TOPSTORIES_FAILURE";
export const TOPSTORIES_DATA = "TOPSTORIES_DATA";

export const BESTSTORIES_REQ = "TOPSTORIES_REQ";
export const BESTSTORIES_SUCCESS = "BESTSTORIES_SUCCESS";
export const BESTSTORIES_FAILURE = "BESTSTORIES_FAILURE";
export const BESTSTORIES_DATA = "BESTSTORIES_DATA";

export const NEWSTORIES_REQ = "NEWSTORIES_REQ";
export const NEWSTORIES_SUCCESS = "NEWSTORIES_SUCCESS";
export const NEWSTORIES_FAILURE = "NEWSTORIES_FAILURE";
export const NEWSTORIES_DATA = "NEWSTORIES_DATA";

